name: fashionext
description: "An Open-Source Fashion App Using Flutter, Flutter Hooks, Django & Django REST Framework"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  flutter_dotenv: ^5.1.0
  flutter_vector_icons: ^2.0.0
  cross_connectivity: ^3.2.0
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  provider: ^6.1.2
  flutter_image_slideshow: ^0.1.6
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  flutter_hooks: ^0.20.5
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^13.2.3
  get_storage: ^2.1.1
  page_view_dot_indicator: ^2.3.0
  flutter_otp_text_field: ^1.1.3+2
  webview_flutter_android: ^3.16.3
  webview_flutter: ^4.8.0
  webview_flutter_wkwebview: ^3.13.1
  webview_universal: ^0.0.5
  google_maps_flutter: ^2.6.1
  get_time_ago: ^1.3.1
  firebase_messaging: ^14.7.21
  flutter_local_notifications: ^17.0.0
  firebase_core: ^2.32.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env.development
    - .env.production

